package.json

- postcss-merge-longhand
> https://github.com/cssnano/cssnano/pull/641

fix: postcss-merge-longhand

---

package.json

https://nodejs.org/en/blog/vulnerability/november-2018-security-releases

feat: node security releases

---

package.json

https://npm.community/t/npm-pack-leaving-out-files-6-8-0-only/5382/5

feat: use npm@6.7.0 instead of npm@6.8.0

---

package.json

https://nodejs.org/en/blog/vulnerability/february-2019-security-releases/

feat: February 2019 Security Releases

---

package.json

terser@3.16.0 makes webpack building failed with error "Cannot read property 'minify' of undefined".
See more detail: <https://github.com/terser-js/terser/issues/251>

fix: Terser TypeError: Cannot read property 'minify' of undefined

---

package.json

https://github.com/npm/hosted-git-info/blob/latest/CHANGELOG.md#280-2019-08-05

feat: use hosted-git-info@2.7.1 instead of 2.8.0

---

package.json

4.8.2版本在centos6中不兼容，后续会在4.8.3版本解决该问题

fix:the alinode-v4.8.2 is not compatible in centos6

---

package.json

auto fix node and alinode unsafe versions
see https://nodejs.org/en/blog/vulnerability/aug-2019-security-releases/

feat: August 2019 Security Releases

---

package.json

https://nodejs.org/en/blog/vulnerability/december-2019-security-releases/

feat: Node.js December 2019 Security Releases

---

package.json

https://nodejs.org/en/blog/vulnerability/february-2020-security-releases/

feat: Node.js February 2020 Security Releases

---

package.json

lodash v4.17.16 and v4.17.17 causing an error of module `lodash/fp` cannot be found.
see `lodash` issue [4846](https://github.com/lodash/lodash/issues/4846), [4848](https://github.com/lodash/lodash/issues/4848).
lodash v4.17.18 causing an error of module `lodash/core` cannot be found.
see `lodash` issue [4850](https://github.com/lodash/lodash/issues/4850).

feat: hotfix lodash@4.17.16-18 to 4.17.15

---

package.json

intl-messageformat@8.4.1 依赖 intl-messageformat-parser@^5.2.1，最近 intl-messageformat-parser 发版了 5.5.x，导致 intl-messageformat 挂掉，也导致我们后续的打包流程挂掉。
报错信息：https://github.com/formatjs/formatjs/issues/2005
相关文件对比：
https://unpkg.com/browse/intl-messageformat-parser@5.5.0/src/skeleton.js
https://unpkg.com/browse/intl-messageformat-parser@5.4.2/src/skeleton.js

fix: intl-messageformat-parser incompatible versions

---

package.json

https://nodejs.org/en/blog/vulnerability/september-2020-security-releases/

feat: Node.js September 2020 Security Releases

---

package.json

caused error:
```
TypeError: Cannot read property 'type' of undefined
```

fix: report eslint-plugin-react bug version v7.21.0

---

package.json

https://nodejs.org/en/blog/vulnerability/november-2020-security-releases/

feat: november 2020 security releases

---

package.json

https://nodejs.org/en/blog/vulnerability/january-2021-security-releases/

feat: Alinode 2021.01 Security Release.

---

package.json

nodejs fs.copyFile 内支持第三个参数为 mode（[见 nodejs fs 代码](https://github.com/nodejs/node/blob/master/lib/fs.js#L2024)），当代码使用 `fs.copyFile` 拷贝文件并指定第三个参数，如 `await fs.copyFile(src, dist, null)` 时
在 graceful-fs@4.2.4 中，由于 graceful-fs 未针对 fs.copyFile 进行特殊处理，因此逻辑正常，在 thenify 中能正常在 callback 中执行 resolve。
在 graceful-fs@4.2.5 中，[由于 graceful-fs 包裹了一层](https://github.com/isaacs/node-graceful-fs/compare/v4.2.4...v4.2.5#diff-05bab169a94002226e0f82bf51c510b4fd2c6cd53f5d558c1ea4136c24a0d7c8R173)，导致第三个参数被 thenify 固定识别为 callback，但实际传入的是 mode，也就是 null，从而导致 resolve 永远无法执行，进而 await 被卡死

fix:graceful-fs fs.copyFile breaking change

---

package.json

https://nodejs.org/en/blog/vulnerability/february-2021-security-releases/
Node.js v10.24.0 (LTS)
Node.js v12.21.0 (LTS)
Node.js v14.16.0 (LTS)
Node.js v15.10.0 (Current)

feat: february 2021 Security Releases

---

package.json

https://nodejs.org/en/blog/vulnerability/february-2021-security-releases/

feat: Alinode 2021.02 Security Release.

---

package.json

https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/167
optimize-css-assets-webpack-plugin 5 个小时前发布了 5.0.7 版本，相比 5.0.6，其中一个变化是 postcss 从传递依赖的 7.x 变为了直接依赖 8.x，导致构建报错。

fix: optimize-css-assets-webpack-plugin@5.0.7 to 5.0.6

---

package.json

https://github.com/cssinjs/jss/issues/1525
他们的一个内部重构搞成了不兼容更新...

fix: react-jss 10.7.0 to 10.6.0

---

package.json

https://nodejs.org/en/blog/vulnerability/july-2021-security-releases/
use the LTS latest version for 12, 14, 16

feat: nodejs july 2021 security releases

---

package.json

```js
var UglifyJS = require("uglify-js");
var code = "function aaa(t) { return t.default; }";
var result = UglifyJS.minify(code, {
ie8: true
});
console.log(result.error); // runtime error, or `undefined` if no error
console.log(result.code);  //
```
**The `uglifyjs` CLI command executed or `minify()` options used.**
in version 3.14.0，the behavior of "default" is not working
**JavaScript output or error produced.**
in version 3.13.10
> function aaa(a){return a["default"]}
in version 3.14.10
> function aaa(a){return a.default}

fix: uglify-js 3.14.0 to 3.13.10

---

package.json

https://github.com/imagemin/gifsicle-bin/issues/133
gifsicle -> post-install -> bin-wrapper -> https://raw.githubusercontent.com/imagemin/gifsicle-bin/v5.3.0/vendor/linux/x64/gifsicle  -> 404

fix: gifsicle 5.3.0->5.2.1

---

package.json

https://nodejs.org/en/blog/vulnerability/jan-2022-security-releases/

feat: january 10th 2022 security releases

---

package.json

math-expression-evaluator 的构建依赖了 webpack@5 但是它声明成了 dependencies 导致很多 webpack@4 的项目构建失败。

 fix: math-expression-evaluator@1.3.12

---

package.json

这个版本会导致 cnpm/tnpm 场景下使用 husky@4 失效。
原因如下，
1、husky 依赖 which-pm-runs 计算 package manager
2、which-pm-runs 4 天前发布了 1.1.0 版本，加上了 cnpm 的处理逻辑，参考 https://github.com/zkochan/packages/commit/e7af82f03f1afe6086312d80a0fa47eb8d1c6bff
3、这本身没有问题，但 husky@4.x 对此没处理好，只通过白名单的方式支持 npm、npminstall、pnpm 和 yarn，加上 cnpm 之后直接退出，参考 https://github.com/typicode/husky/blob/v4.3.8/sh/husky.sh#L84-L90 ，这让使用 cnpm 或 tnpm 安装 husky@4 时 pre-commit 直接失效
临时方案，
修改 .git/hooks/husky.local.sh，替换 cnpm 为 npm。

fix: add which-pm-runs@1.1.0

---

package.json

https://github.com/RIAEvangelist/node-ipc/issues/233

fix: node-ipc

---

package.json

see https://nodejs.org/en/blog/vulnerability/mar-2022-security-releases/

feat: openssl security releases require Node.js security releases

---

package.json
test.js

Follow https://github.com/npm/rfcs/pull/488

feat: support override scripts config

---

package.json

Reverts cnpm/bug-versions#192
https://github.com/babel/minify/issues/1028#issuecomment-1114982399
这个是babel-minify依赖了有bug的行为，babel-traverse本身没问题

Revert "fix: lock babel-traverse 7.17.10 to 7.17.9"

---

package.json
test.js

The project has been moved to the `nodejs` org https://github.com/nodejs/node-core-test and has the new npm name `test`.

chore: switch from `node-core-test` to `test`

---

package.json

Related: https://github.com/cnpm/bug-versions/pull/174
Restore `which-pm-runs@1.1.0` if `husky` has already fixed the issue.

fix: restore which-pm-runs@1.1.0

---

package.json

https://nodejs.org/en/blog/vulnerability/july-2022-security-releases/

feat: nodejs july 7th 2020 security releases

---

package.json

This reverts commit bdb157e09e67f1ecf93e54eabf4328ed6ebd36ff.
closes https://github.com/cnpm/cnpm/issues/396

Revert "fix: express-serve-static-core typings for ts3 (#207)"

---

package.json

https://nodejs.org/en/blog/vulnerability/september-2022-security-releases/

feat: node September 22nd 2022 Security Releases

---

.github/workflows/nodejs.yml
package.json

https://nodejs.org/en/blog/vulnerability/november-2022-security-releases/

feat: nodejs Security Release target November 4th 2022

---

package.json

https://github.com/imagemin/gifsicle-bin/issues/133#issuecomment-979906835
https://www.npmjs.com/package/gifsicle/v/5.3.0
Author has released version 5.3.0.

fix: Remove gifsicle 5.3.0 -> 5.2.1 overrides

---

package.json

具体服务：https://github.com/YvesCoding/vuescroll/issues/285

feat: 增加vuescroll@4.17.4,原因是依赖的服务问题导致不可用

---

package.json

issue来源： https://github.com/estools/esquery/issues/135

feat: 增加esquery@1.4.1，原因是会导致eslint报错不可用

---

package.json

https://nodejs.org/en/blog/vulnerability/february-2023-security-releases/
closes https://github.com/cnpm/bug-versions/issues/224

feat: nodejs thursday february 16 2023 security releases

---

package.json

> alertify.js has set snyk in deps, which causes the snyk postinstall script to be triggered. alertify.js seems to alertify.js has stopped updating. https://github.com/alertifyjs/alertify.js/issues/160
* 🔄 Downgrade alertify.js from version `1.0.2` to `1.0.1`
--------------
> alertify.js 在 deps 中依赖了 snyk ，导致默认触发 snyk 的 postinstall 脚本，目前似乎已经停止更新 https://github.com/alertifyjs/alertify.js/issues/160
* ♻️ 将 alertify.js 的 `1.0.2` 版本指向 `1.0.1`

feat: add alertify.js

---

package.json

json-schema-faker 0.5.0 为空包，实际没有任何代码文件

feat: adds json-schema-faker 0.5.0

---

package.json

https://nodejs.org/en/blog/vulnerability/june-2023-security-releases

feat: node.js tuesday june 20 2023 security releases

---

package.json

https://nodejs.org/en/blog/vulnerability/february-2024-security-releases/

feat: node.js wednesday february 14 2024 security releases
